/**
 * World Builder routes — CRUD for player-placed objects and Tiled map overrides.
 *
 * Placed objects table stores two kinds of records:
 *   "placed"          — new objects added by the world builder
 *   "tiled_tombstone" — marks a Tiled-static object as deleted (client skips it on load)
 *
 * When deleting a standalone Tiled wall object we also attempt to remove it from the
 * Tiled JSON on disk so the change survives server restarts.
 */

import type { FastifyInstance } from "fastify";
import { db } from "../db/postgres.js";
import { placedObjects } from "../db/schema.js";
import { eq, and } from "drizzle-orm";
import { getZone } from "../game/zone-registry.js";
import { readFile, writeFile } from "fs/promises";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MAPS_DIR = resolve(__dirname, "../../../../packages/client/public/maps");

export async function worldBuilderRoutes(app: FastifyInstance) {
  // GET /api/world-builder/:zoneId
  // Returns all placed objects and tiled tombstones for a zone.
  app.get<{ Params: { zoneId: string } }>("/:zoneId", async (req) => {
    const { zoneId } = req.params;
    const rows = await db.select().from(placedObjects).where(eq(placedObjects.zoneId, zoneId));
    return { objects: rows };
  });

  // POST /api/world-builder/:zoneId
  // Persist a newly placed object.
  app.post<{
    Params: { zoneId: string };
    Body: {
      tileX: number; tileZ: number; pieceType: string; material: string;
      elevation?: number; flip?: boolean; flipL?: boolean; flipR?: boolean;
    };
  }>("/:zoneId", async (req) => {
    const { zoneId } = req.params;
    const { tileX, tileZ, pieceType, material, elevation, flip, flipL, flipR } = req.body;
    const [row] = await db
      .insert(placedObjects)
      .values({
        zoneId, tileX, tileZ, pieceType,
        material: material || "stone",
        elevation: elevation ?? 0,
        flip: flip ?? false,
        flipL: flipL ?? false,
        flipR: flipR ?? false,
        source: "placed",
      })
      .returning();
    return { object: row };
  });

  // DELETE /api/world-builder/:id
  // Delete a placed object. If the id is "tiled:{zoneId}:{tileX},{tileZ},{pieceType}",
  // creates a tombstone and attempts to remove the piece from the Tiled JSON file.
  app.delete<{
    Params: { id: string };
    Body?: { tileX?: number; tileZ?: number; pieceType?: string; zoneId?: string; material?: string };
  }>("/:id", async (req) => {
    const { id } = req.params;

    if (id.startsWith("tiled:")) {
      const { tileX, tileZ, pieceType, zoneId, material } = req.body ?? {};
      if (tileX == null || tileZ == null || !pieceType || !zoneId) {
        return { deleted: false, reason: "missing tiled piece info" };
      }
      // Insert tombstone
      const [row] = await db
        .insert(placedObjects)
        .values({ zoneId, tileX, tileZ, pieceType, material: material ?? "stone", source: "tiled_tombstone" })
        .returning({ id: placedObjects.id });
      // Best-effort Tiled JSON modification
      applyTiledDeletion(zoneId, tileX, tileZ, pieceType).catch(e =>
        console.warn("[WB] Tiled JSON write failed:", e));
      return { deleted: true, tombstoneId: row.id };
    }

    // Delete placed object from DB
    await db.delete(placedObjects).where(eq(placedObjects.id, id));
    return { deleted: true };
  });

  // PUT /api/world-builder/:id/move
  // Relocate a placed object.
  app.put<{ Params: { id: string }; Body: { tileX: number; tileZ: number } }>(
    "/:id/move",
    async (req) => {
      const { id } = req.params;
      const { tileX, tileZ } = req.body;
      await db.update(placedObjects).set({ tileX, tileZ }).where(eq(placedObjects.id, id));
      return { updated: true };
    },
  );
}

// ─── Tiled JSON helper ────────────────────────────────────────────────────────

/**
 * Attempt to remove a standalone "wall" object from the Tiled JSON on disk.
 * Objects generated by a "building" composite cannot be individually targeted
 * here — the tombstone in the DB is enough for those.
 */
async function applyTiledDeletion(
  zoneId: string, tileX: number, tileZ: number, pieceType: string,
): Promise<void> {
  const zone = getZone(zoneId);
  if (!zone) return;

  const mapPath = resolve(MAPS_DIR, zone.mapFile);
  const raw = await readFile(mapPath, "utf8");
  const json = JSON.parse(raw);

  let changed = false;
  for (const layer of json.layers as any[]) {
    if (layer.type !== "objectgroup") continue;
    const before = layer.objects.length;
    layer.objects = layer.objects.filter((obj: any) => {
      if (obj.type !== "wall") return true;
      const objTileX = Math.floor(obj.x / json.tilewidth);
      const objTileZ = Math.floor(obj.y / json.tileheight);
      const props: Record<string, any> = {};
      for (const p of (obj.properties ?? [])) props[p.name] = p.value;
      if (objTileX === tileX && objTileZ === tileZ && props.type === pieceType) {
        changed = true;
        return false;
      }
      return true;
    });
    if (layer.objects.length < before) break;
  }

  if (changed) {
    await writeFile(mapPath, JSON.stringify(json, null, 2), "utf8");
    console.log(`[WB] Removed wall (${tileX},${tileZ},${pieceType}) from ${zone.mapFile}`);
  }
}
