/**
 * Tileset index — loads every registered TSX file (see ./registry/tilesets)
 * and exposes a flat list of "tile entries" for the picker, the brush
 * ghost, and on-map rendering.
 *
 * Categorisation, layer defaults, and collision flags come from the
 * registry; this file is now purely about IO + indexing. To add a new
 * tileset, append to `registry/tilesets.ts` — no changes here.
 *
 * Every tileset is loaded as BOTH a raw HTMLImageElement (for the HTML tile
 * picker previews) AND an Excalibur ImageSource (for in-game rendering).
 * Both reuse the same decoded bitmap via `ImageSource.fromHtmlImageElement`.
 */
import { ImageSource, Sprite, Animation, AnimationStrategy, SpriteSheet } from "excalibur";
import { listTilesets, matchSubRegion, type TilesetDef } from "./registry/tilesets.js";
import type { CategoryId } from "./registry/categories.js";
import type { LayerId }    from "./registry/layers.js";
import { getOverride }     from "./registry/overrides.js";
import emptyTilesManifest  from "./registry/empty-tiles.json";

/** Static manifest of fully-transparent (empty) tile IDs per tileset file.
 *  Generated by running `__builder.dumpEmptyTiles()` in the browser console
 *  and pasting into `registry/empty-tiles.json`. Empty tiles are skipped
 *  entirely — they never become TileEntry objects, don't take up memory in
 *  the picker, and can't be revealed via overrides.
 *
 *  Sheets NOT in the manifest fall back to a runtime scan (so newly added
 *  tilesets still get auto-cleaned on first load; re-dump and re-bake to
 *  make them static). */
const EMPTY_TILES: Record<string, number[]> = emptyTilesManifest as Record<string, number[]>;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface AnimationFrame {
  tileId:   number;
  duration: number;  // ms
}

export interface TileEntry {
  /** TSX filename (path relative to /maps/). Unique key for lookups. */
  tileset:   string;
  /** Local tile id inside the TSX (row-major, 0-based). */
  tileId:    number;
  /** Pixel source rect inside the tileset image. */
  sx:        number;
  sy:        number;
  sw:        number;
  sh:        number;
  /** When present, this tile is animated. Frame 0 is the base sprite. */
  animation?: AnimationFrame[];
  /** Resolved category after applying subRegions (may differ from the
   *  tileset's default category). */
  category:  CategoryId;
  /** Whether this specific tile blocks player movement. */
  blocks:    boolean;
  /** Preferred placement layer for this tile. */
  defaultLayer: LayerId;
  /** Searchable label (human-readable). */
  label:     string;
  /** Grid position inside the tileset. */
  col:       number;
  row:       number;
  /** When true, this tile is excluded from the picker.
   *  Set by an explicit `hide:true` SubRegion or by the auto-label scanner. */
  hidden:    boolean;
}

export interface TilesetMeta {
  file:        string;          // path relative to /maps/
  name:        string;          // display name from TSX
  tilewidth:   number;
  tileheight:  number;
  columns:     number;
  tilecount:   number;
  imageUrl:    string;          // resolved absolute URL to the PNG
  imageWidth:  number;
  imageHeight: number;
  /** Loaded image bitmap. Null until loadImage() resolves. */
  image:       HTMLImageElement | null;
  /** Excalibur ImageSource wrapping the same image; null until loaded. */
  exImage:     ImageSource | null;
  /** Excalibur spritesheet over the whole tileset. */
  exSheet:     SpriteSheet | null;
  /** Per-tileId animation frames, if any. */
  animations:  Map<number, AnimationFrame[]>;
  /** Tile IDs that are fully transparent (empty cells in the sheet).
   *  Sourced first from the static `empty-tiles.json` manifest; if the sheet
   *  isn't in the manifest, filled by a one-off runtime scan.
   *  Empty tiles are deleted from the index — they never become TileEntry
   *  objects. The set is kept for debugging / dump-to-manifest. */
  emptyTiles:  Set<number>;
  /** Registry entry this tileset was loaded from. */
  def:         TilesetDef;
  /** Sparse array indexed by tileId. Empty tiles leave holes. Use
   *  `allEntries()` / iteration helpers which skip the holes. */
  entries:     (TileEntry | undefined)[];
}

// ---------------------------------------------------------------------------
// TSX parser (regex, zero deps)
// ---------------------------------------------------------------------------

function attr(src: string, key: string): string | undefined {
  const re = new RegExp(`\\b${key}="([^"]*)"`);
  return src.match(re)?.[1];
}

function requireAttr(src: string, key: string): string {
  const v = attr(src, key);
  if (v === undefined) throw new Error(`Missing attribute '${key}'`);
  return v;
}

/** Encode spaces/special chars per path segment but leave the `.tsx`
 *  extension unencoded. Vite's dev server treats encoded `.tsx` requests as
 *  React component files and serves index.html instead of the tileset, so we
 *  have to be careful with the encoding. Browsers do URL-encode spaces
 *  during fetch automatically, so only commas/parentheses need attention. */
function encodePath(path: string): string {
  return path.split("/").map((seg) => {
    // Encode characters that break the URL parser but leave reserved chars
    // like `.`, `(`, `)`, `,` alone. Space will be auto-encoded by fetch.
    return seg.replace(/[#?&=]/g, encodeURIComponent);
  }).join("/");
}

function parseTsxXml(xml: string, def: TilesetDef): TilesetMeta {
  const tsHead = xml.match(/<tileset\b([^>]*)>/);
  if (!tsHead) throw new Error(`No <tileset> in ${def.file}`);
  const tsAttrs = tsHead[1];

  const imgMatch = xml.match(/<image\b([^>]*?)\/>/);
  if (!imgMatch) throw new Error(`No <image> in ${def.file}`);
  const imgAttrs = imgMatch[1];

  const imgSrc = requireAttr(imgAttrs, "source");
  const imageUrl = resolveRelative(`/maps/${def.file}`, imgSrc);

  const meta: TilesetMeta = {
    file:        def.file,
    name:        requireAttr(tsAttrs, "name"),
    tilewidth:   +requireAttr(tsAttrs, "tilewidth"),
    tileheight:  +requireAttr(tsAttrs, "tileheight"),
    tilecount:   +requireAttr(tsAttrs, "tilecount"),
    columns:     +requireAttr(tsAttrs, "columns"),
    imageUrl,
    imageWidth:  +requireAttr(imgAttrs, "width"),
    imageHeight: +requireAttr(imgAttrs, "height"),
    image:       null,
    exImage:     null,
    exSheet:     null,
    animations:  new Map(),
    emptyTiles:  new Set(),
    def,
    entries:     [],
  };

  // Parse animations.
  //   <tile id="N"><animation><frame tileid="M" duration="D"/>...</animation></tile>
  const tileRe = /<tile\b([^>]*)>([\s\S]*?)<\/tile>/g;
  let m: RegExpExecArray | null;
  while ((m = tileRe.exec(xml)) !== null) {
    const id = +requireAttr(m[1], "id");
    const body = m[2];
    const animMatch = body.match(/<animation>([\s\S]*?)<\/animation>/);
    if (!animMatch) continue;
    const frames: AnimationFrame[] = [];
    const frameRe = /<frame\b([^/]*)\/>/g;
    let fm: RegExpExecArray | null;
    while ((fm = frameRe.exec(animMatch[1])) !== null) {
      frames.push({
        tileId:   +requireAttr(fm[1], "tileid"),
        duration: +requireAttr(fm[1], "duration"),
      });
    }
    if (frames.length > 0) meta.animations.set(id, frames);
  }

  return meta;
}

/** Resolve a relative image source against the TSX's URL. */
function resolveRelative(baseUrl: string, relative: string): string {
  const parts = baseUrl.split("/").slice(0, -1); // drop filename
  for (const seg of relative.split("/")) {
    if (seg === "..") parts.pop();
    else if (seg === ".") { /* skip */ }
    else parts.push(seg);
  }
  return parts.join("/");
}

// ---------------------------------------------------------------------------
// Entry generation — applies subRegion overrides on top of tileset defaults
// ---------------------------------------------------------------------------

/** Build entries from definition + sub-regions + author overrides.
 *  Order of precedence: TilesetDef → SubRegion → Override (last wins).
 *  Called once at load and again whenever an override changes.
 *
 *  Empty tiles (fully transparent) are skipped entirely — `meta.entries[i]`
 *  stays undefined for those IDs. They never become TileEntry objects,
 *  save picker memory, and can't be revealed (intentional — they're not
 *  real tiles, just unused cells). */
export function buildEntries(meta: TilesetMeta): void {
  // Reset to a clean sparse array of the right length. Empty tile IDs stay
  // as holes (no allocation); tileId-indexed lookups still work via
  // `entries[id]`.
  meta.entries.length = 0;
  meta.entries.length = meta.tilecount;

  const def = meta.def;
  const baseCategory     = def.category;
  const baseBlocks       = def.blocks ?? false;
  const baseDefaultLayer = def.defaultLayer ?? "ground";

  for (let i = 0; i < meta.tilecount; i++) {
    if (meta.emptyTiles.has(i)) continue;  // skip empty cells entirely

    const col = i % meta.columns;
    const row = Math.floor(i / meta.columns);
    const sr  = matchSubRegion(def, i);
    const ov  = getOverride(meta.file, i);

    const category     = ov?.category     ?? sr?.category     ?? baseCategory;
    const blocks       = ov?.blocks       ?? sr?.blocks       ?? baseBlocks;
    const defaultLayer = ov?.defaultLayer ?? sr?.defaultLayer ?? baseDefaultLayer;
    const animation    = meta.animations.get(i);
    const animSuffix   = animation && animation.length > 1 ? "⟳" : "";
    const baseLabel    = sr?.label
      ? `${sr.label} — ${meta.name} #${i}${animSuffix}`
      : `${meta.name} #${i}${animSuffix}`;
    const label        = ov?.name ? `${ov.name} (${meta.name} #${i})${animSuffix}` : baseLabel;
    const hidden       = ov?.hide ?? sr?.hide ?? false;

    meta.entries[i] = {
      tileset:      meta.file,
      tileId:       i,
      sx:           col * meta.tilewidth,
      sy:           row * meta.tileheight,
      sw:           meta.tilewidth,
      sh:           meta.tileheight,
      animation,
      category,
      blocks,
      defaultLayer,
      label,
      col, row,
      hidden,
    };
  }
}

// ---------------------------------------------------------------------------
// Public TilesetIndex
// ---------------------------------------------------------------------------

export class TilesetIndex {
  readonly tilesets = new Map<string, TilesetMeta>();
  private ready: Promise<void> | null = null;

  /** Load every registered TSX + its image. Idempotent. */
  load(): Promise<void> {
    if (!this.ready) this.ready = this.doLoad();
    return this.ready;
  }

  private async doLoad(): Promise<void> {
    let totalEmpty = 0;
    let manifested = 0;
    let scanned    = 0;
    await Promise.all(listTilesets().map(async (def) => {
      try {
        const res = await fetch(`/maps/${encodePath(def.file)}`);
        if (!res.ok) { console.warn(`[Tiles] Missing ${def.file} (${res.status})`); return; }
        const xml = await res.text();
        const meta = parseTsxXml(xml, def);
        meta.image = await loadImage(meta.imageUrl);

        // Wrap the same decoded image in an Excalibur ImageSource (no second
        // network fetch). Build a spritesheet spanning the whole tileset.
        meta.exImage = ImageSource.fromHtmlImageElement(meta.image);
        await meta.exImage.load();
        meta.exSheet = SpriteSheet.fromImageSource({
          image: meta.exImage,
          grid:  {
            rows:         Math.ceil(meta.tilecount / meta.columns),
            columns:      meta.columns,
            spriteWidth:  meta.tilewidth,
            spriteHeight: meta.tileheight,
          },
        });

        // Empty-tile source of truth: static manifest first, runtime scan
        // only if the sheet isn't in the manifest (e.g. freshly registered).
        // Sheets in the manifest cost zero canvas reads at load; sheets not
        // in the manifest pay the one-time scan so they're still auto-cleaned.
        const manifest = EMPTY_TILES[def.file];
        if (manifest) {
          for (const id of manifest) meta.emptyTiles.add(id);
          manifested++;
        } else {
          detectEmptyTiles(meta);
          if (meta.emptyTiles.size > 0) scanned++;
        }
        totalEmpty += meta.emptyTiles.size;

        buildEntries(meta);
        this.tilesets.set(def.file, meta);
      } catch (err) {
        console.warn(`[Tiles] Failed to load ${def.file}:`, err);
      }
    }));
    console.log(
      `[Tiles] Indexed ${this.tilesets.size} tileset(s), ` +
      `${this.allEntries().length} visible tile(s); ` +
      `${totalEmpty} empty tile(s) deleted ` +
      `(${manifested} from manifest, ${scanned} scanned live)`,
    );
  }

  /** Static Sprite for a tile (or null if tileset not loaded). */
  makeSprite(tileset: string, tileId: number): Sprite | null {
    const meta = this.tilesets.get(tileset);
    if (!meta || !meta.exSheet) return null;
    const col = tileId % meta.columns;
    const row = Math.floor(tileId / meta.columns);
    return meta.exSheet.getSprite(col, row);
  }

  /** Animation for animated tiles, Sprite for static tiles, null on miss. */
  makeGraphic(tileset: string, tileId: number): Sprite | Animation | null {
    const meta = this.tilesets.get(tileset);
    if (!meta || !meta.exSheet) return null;
    const anim = meta.animations.get(tileId);
    if (!anim || anim.length <= 1) {
      return this.makeSprite(tileset, tileId);
    }
    const frames = anim.map((f) => {
      const col = f.tileId % meta.columns;
      const row = Math.floor(f.tileId / meta.columns);
      return { graphic: meta.exSheet!.getSprite(col, row), duration: f.duration };
    });
    return new Animation({ frames, strategy: AnimationStrategy.Loop });
  }

  getTileset(file: string): TilesetMeta | undefined {
    return this.tilesets.get(file);
  }

  allEntries(): TileEntry[] {
    const out: TileEntry[] = [];
    for (const t of this.tilesets.values()) {
      if (t.def.hidden) continue;
      for (const e of t.entries) {
        if (!e || e.hidden) continue;  // skip sparse holes + hidden entries
        out.push(e);
      }
    }
    return out;
  }

  /** Unique categories that currently have at least one tile, sorted. */
  categoriesWithTiles(): CategoryId[] {
    const s = new Set<CategoryId>();
    for (const t of this.tilesets.values()) {
      if (t.def.hidden) continue;
      for (const e of t.entries) {
        if (!e) continue;
        s.add(e.category);
      }
    }
    return Array.from(s);
  }

  /** Filter entries by category (null = all) and optional text query. */
  filter(category: CategoryId | null, query: string): TileEntry[] {
    const q = query.trim().toLowerCase();
    const all = this.allEntries();
    return all.filter((e) => {
      if (category && e.category !== category) return false;
      if (!q) return true;
      const ts = this.tilesets.get(e.tileset);
      const tags = ts?.def.tags?.join(" ") ?? "";
      return e.label.toLowerCase().includes(q)
          || e.tileset.toLowerCase().includes(q)
          || e.category.toLowerCase().includes(q)
          || tags.toLowerCase().includes(q);
    });
  }

  /** Lookup a single tile entry by (tileset, tileId). */
  find(tileset: string, tileId: number): TileEntry | undefined {
    const ts = this.tilesets.get(tileset);
    return ts?.entries[tileId];
  }

  /** Re-build entries for one tileset after an override changes. */
  refreshEntries(tileset: string): void {
    const ts = this.tilesets.get(tileset);
    if (!ts) return;
    buildEntries(ts);
  }

  /** Force a live pixel scan of every tileset and return the manifest.
   *  Used by `__builder.dumpEmptyTiles()` to produce a fresh JSON blob
   *  for pasting into `registry/empty-tiles.json` when new sheets are added
   *  (or when we want to re-verify). Ignores the static manifest entirely. */
  rescanEmptyTiles(): Record<string, number[]> {
    const out: Record<string, number[]> = {};
    for (const [file, meta] of this.tilesets) {
      meta.emptyTiles.clear();
      detectEmptyTiles(meta);
      if (meta.emptyTiles.size > 0) {
        out[file] = Array.from(meta.emptyTiles).sort((a, b) => a - b);
      }
      // Rebuild entries so the picker reflects the rescan even if nothing
      // changed — cheap and keeps state consistent.
      buildEntries(meta);
    }
    return out;
  }
}

// ---------------------------------------------------------------------------
// Empty-tile detector — flags cells where every sampled pixel is fully
// transparent (alpha < 4). Used to remove blank cells reserved for future
// expansion in Mana Seed sheets from the picker.
// ---------------------------------------------------------------------------

const ALPHA_THRESHOLD = 4;

/** Re-uses one offscreen canvas across all tilesets to avoid GC churn. */
let scratchCanvas: HTMLCanvasElement | null = null;
let scratchCtx:    CanvasRenderingContext2D | null = null;

function getScratch(): { ctx: CanvasRenderingContext2D; canvas: HTMLCanvasElement } | null {
  if (!scratchCanvas) {
    scratchCanvas = document.createElement("canvas");
    scratchCtx    = scratchCanvas.getContext("2d", { willReadFrequently: true });
  }
  return scratchCtx ? { ctx: scratchCtx, canvas: scratchCanvas } : null;
}

function detectEmptyTiles(meta: TilesetMeta): void {
  if (!meta.image) return;
  const s = getScratch();
  if (!s) return;
  const { ctx, canvas } = s;
  if (canvas.width !== meta.imageWidth || canvas.height !== meta.imageHeight) {
    canvas.width  = meta.imageWidth;
    canvas.height = meta.imageHeight;
  }
  ctx.imageSmoothingEnabled = false;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.drawImage(meta.image, 0, 0);

  const tw = meta.tilewidth;
  const th = meta.tileheight;
  const cols = meta.columns;

  for (let i = 0; i < meta.tilecount; i++) {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const sx  = col * tw;
    const sy  = row * th;
    if (isTileFullyTransparent(ctx, sx, sy, tw, th)) {
      meta.emptyTiles.add(i);
    }
  }
}

/** True if every pixel in the tile rect has alpha < ALPHA_THRESHOLD.
 *  Reads the rect in one getImageData call (cheaper than per-pixel calls). */
function isTileFullyTransparent(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number,
): boolean {
  const data = ctx.getImageData(x, y, w, h).data;
  // Iterate over alpha channel only (every 4th byte).
  for (let i = 3; i < data.length; i += 4) {
    if (data[i] >= ALPHA_THRESHOLD) return false;
  }
  return true;
}

// ---------------------------------------------------------------------------
// Image loader
// ---------------------------------------------------------------------------

const imageCache = new Map<string, Promise<HTMLImageElement>>();

function loadImage(url: string): Promise<HTMLImageElement> {
  let p = imageCache.get(url);
  if (!p) {
    p = new Promise<HTMLImageElement>((resolve, reject) => {
      const img = new Image();
      img.onload  = () => resolve(img);
      img.onerror = () => reject(new Error(`Failed to load image: ${url}`));
      img.src = url;
    });
    imageCache.set(url, p);
  }
  return p;
}
